MPI = true

# incident spectrum
grid = 'bc03_miles_chabrier_a50'
age_lim = 30 # Myr

# GEOMETRY
geometry = 'spherical'
radius = 3  # radius of the cloud, in parsecs

# IONISATION PARAMETER 
# ionisation_parameter_model: ref  # which ionisation parameter model to use. `ref` assumes a varying ionisation parameter at a fixed reference age and metallicity
# reference_ionisation_parameter: 0.01  # value of ionisation parameter at reference value, for U_model='ref'
# reference_age: 1.0e+6  # log10(age/year) at which to set reference ionisation parameter, for U_model='ref'
# reference_metallicity: 0.01  # metallicity at which to set reference ionisation parameter, for U_model='ref'

cosmic_rays = true  # flag for inclusion of cosmic ray heating
constant_density = true
constant_pressure = false

iterate_to_convergence = true
# T_floor = 100  # lower gas temperature floor
# STOPPING CRITERIA
# stop_T = 500  # stopping temperature
# stop_efrac = -2  # limiting ratio of electron to H densities
# stop_column_density = 20.5

# MISC COMMANDS
# cmd = true
# z = 0

# # OUTPUT COMMANDS
# resolution: 1.0 # energy resolution relative to the default
# output_cont: true
# output_linelist: linelist-standard.dat

[abundances]
    model = 'Gutkin16'


# # GRID COMMANDS
[logU]
    # fixed = true
    # value = -2.0
    fixed = false
    low = -4
    high = -1
    step = 0.5

[lognH]
    fixed = true
    value = 2.0
    
    # fixed = false
    # low = 1
    # high = 5
    # step = 0.5

[xid]
    fixed = true
    value = 0.36

[CO]
    fixed = true
    value = 1.0
